### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null Error upon opening Forge

### ISSUE THREAD

**Issue by ReiNAce** [sa-shiro/Minecraft-Compressed-Blocks#10]
CB: Compressed Blocks ver 6.0.0
Forge ver 37.0.71
Minecraft ver 1.17.1

Upon opening MC Forge, this error comes up. I'm sorry I can't help with the debugging as I have no background in programming. I attached the MC screenshot error together with the log and crash report that may help you find the bug. This error comes when I opened forge after dragging the jar file in my mods folder in .minecraft

I hope you can find the bug. Thank you for your patience and time.
<img width="426" alt="error" src="https://user-images.githubusercontent.com/92549946/137393796-673e37c8-7e86-4173-8744-b505593df2cc.png">
[crash-2021-10-15_04.23.20-fml.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/7349310/crash-2021-10-15_04.23.20-fml.txt)
[latest.log](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/7349312/latest.log)

**Comment by sa-shiro** [comment]
This is due to the newer forge, 
The current release has been compiled with the beta version of forge so it can be expected to crash with the latest forge (changes within forge -> methods, names etc)

ive been very busy and i had to refresh my computer, i will re-setup an dev environment and will build a new version with the latest forge

**Comment by sa-shiro** [comment]
@ReiNAce 
I did not test if the "minable" tag works for every block, i just tested a few of them so please let me know if you find any blocks that arent dropping itself upon breaking (the majority of the blocks requires the correct tool ofc).
